# Generated by Django 4.1.2 on 2022-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasadía', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasadia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pasadia'),
        ),
    ]
