# Generated by Django 4.1.2 on 2022-12-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasadía', '0002_pasadia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion_pasadia',
            name='cantidad_habitaciones',
        ),
    ]
