# Generated by Django 4.1.2 on 2022-11-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=50)),
                ('apellido1_solicitante', models.CharField(max_length=50)),
                ('apellido2_solicitante', models.CharField(max_length=50)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('carnet', models.PositiveBigIntegerField()),
                ('estado', models.CharField(choices=[('env', 'Enviada'), ('ace', 'Aceptada'), ('can', 'Cancelada'), ('pag', 'Pagada')], default='env', max_length=3)),
                ('total_de_personas', models.IntegerField()),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
