# Generated by Django 4.1.2 on 2022-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0002_alter_reservacion_options_items_reservacion_adultos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_reservacion',
            name='total',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
