# Generated by Django 4.1.2 on 2022-11-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0004_remove_reservacion_monto_a_pagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
