# Generated by Django 4.1.2 on 2022-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0006_reservacion_telefono_alter_reservacion_carnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_reservacion',
            name='cantidad_habitaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
