# Generated by Django 4.1.2 on 2022-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0008_reservacion_codigo_reservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='codigo_reservacion',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
