# Generated by Django 4.0.2 on 2022-10-17 04:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cadena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('polo', models.CharField(max_length=11)),
                ('descripcion', models.TextField()),
                ('categoria', models.PositiveSmallIntegerField(default=1, help_text='Cantidad de estrellas entre 1 y 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activo', models.BooleanField()),
                ('cadena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.cadena')),
            ],
        ),
    ]
