# Generated by Django 4.0.2 on 2022-10-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'hoteles'},
        ),
        migrations.RenameField(
            model_name='cadena',
            old_name='nombre_cadena',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cadena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='hotel.cadena'),
        ),
    ]
