# Generated by Django 4.0.2 on 2022-10-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='hotel'),
        ),
    ]
