# Generated by Django 4.1.2 on 2022-10-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='polo',
            field=models.CharField(choices=[('occ', 'occidente'), ('cen', 'centro'), ('ori', 'oriente')], default='occ', max_length=3, null=b'I00\n'),
        ),
    ]
