# Generated by Django 4.1.2 on 2022-11-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_polo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=20)),
                ('fecha_inicial_vigente', models.DateField()),
                ('fecha_final_vigente', models.DateField()),
                ('fecha_inicial_reserva', models.DateField()),
                ('fecha_final_reserva', models.DateField()),
                ('tipo_habitacion', models.CharField(choices=[('sen', 'sencilla'), ('dob', 'doble'), ('tri', 'triple')], default='sen', max_length=3, null=b'I00\n')),
                ('precio_adulto', models.FloatField()),
                ('precio_primer_niño', models.FloatField()),
                ('precio_segundo_niño', models.FloatField()),
                ('precio_tercer_niño', models.FloatField()),
                ('suplemento', models.FloatField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='hotel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='hotel.hotel')),
            ],
        ),
    ]
