# Generated by Django 4.1.2 on 2022-11-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_oferta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name_plural': 'ofertas'},
        ),
    ]
