# Generated by Django 4.1.2 on 2022-11-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_oferta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='precio_primer_niño',
            new_name='precio_primer_ninno',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='precio_segundo_niño',
            new_name='precio_segundo_ninno',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='precio_tercer_niño',
            new_name='precio_tercer_ninno',
        ),
    ]
