# Generated by Django 4.1.2 on 2022-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_precio_primer_niño_oferta_precio_primer_ninno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tipo_habitacion',
            field=models.CharField(choices=[('sencilla', 'sencilla'), ('doble', 'doble'), ('triple', 'triple')], default='sencilla', max_length=8, null=b'I00\n'),
        ),
    ]
