# Generated by Django 4.1.2 on 2022-11-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_oferta_tipo_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='cant_max_adulto',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='oferta',
            name='cant_max_ninnos',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='oferta',
            name='cant_min_adulto',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='oferta',
            name='cant_min_ninnos',
            field=models.IntegerField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_habitacion',
            field=models.CharField(choices=[('sencilla', 'Sencilla'), ('doble', 'Doble'), ('triple', 'Triple')], default='sencilla', max_length=8, null=b'I00\n'),
        ),
    ]
