# Generated by Django 4.1.2 on 2022-11-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_oferta_cant_max_adulto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='polo',
            field=models.CharField(choices=[('occ', 'occidente'), ('cen', 'centro'), ('ori', 'oriente')], default='occ', max_length=3),
        ),
    ]
