# Generated by Django 4.1.2 on 2022-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_hotel_polo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='precio_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
