# Generated by Django 4.1.2 on 2022-11-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_hotel_precio_transporte_hotel_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
