# Generated by Django 4.1.2 on 2022-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_hotel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='suplemento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
