# Generated by Django 4.1.2 on 2022-11-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_hotel_polo_alter_hotel_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='precio_segundo_ninno',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='precio_tercer_ninno',
        ),
    ]
