# Generated by Django 4.1.2 on 2022-11-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': 'contactos'},
        ),
    ]
