# Generated by Django 4.1.2 on 2022-11-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_oferta_dias_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='dias_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
