# Generated by Django 4.1.2 on 2022-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_oferta_dias_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(default='oferta/3.png', null=True, upload_to='oferta'),
        ),
    ]
