# Generated by Django 4.1.2 on 2022-12-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0025_alter_oferta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_Especial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('fecha_inicial', models.DateField(null=True)),
                ('fecha_final', models.DateField(null=True)),
                ('total_de_personas', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_especiales', to='hotel.hotel')),
            ],
            options={
                'verbose_name_plural': 'Ofertas especiales',
            },
        ),
    ]
