# Generated by Django 4.1.2 on 2022-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion_especial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_especial',
            name='fecha_final_vigente',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='oferta_especial',
            name='fecha_inicial_vigente',
            field=models.DateField(null=True),
        ),
    ]
