# Generated by Django 4.1.2 on 2022-12-09 12:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion_especial', '0002_oferta_especial_fecha_final_vigente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion_Especial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reservacion', models.PositiveIntegerField(blank=True, default=0)),
                ('nombre_solicitante', models.CharField(max_length=50, null=True)),
                ('apellido1_solicitante', models.CharField(max_length=50, null=True)),
                ('apellido2_solicitante', models.CharField(max_length=50, null=True)),
                ('carnet', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.TextField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('estado', models.CharField(choices=[('env', 'Enviada'), ('ace', 'Aceptada'), ('can', 'Cancelada'), ('pag', 'Pagada')], default='env', max_length=3)),
                ('transporte', models.BooleanField(default=False)),
                ('ofeta_especial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservación_especial', to='reservacion_especial.oferta_especial')),
            ],
            options={
                'verbose_name_plural': 'Reservaciones especiales',
            },
        ),
    ]
