# Generated by Django 4.1.2 on 2022-12-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_oferta_imagen'),
        ('reservacion_especial', '0003_reservacion_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion_especial',
            name='ofeta_especial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_especial', to='reservacion_especial.oferta_especial'),
        ),
        migrations.CreateModel(
            name='Items_Reservacion_Especial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitaciones', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adultos', models.PositiveIntegerField(default=0, null=True)),
                ('ninnos', models.PositiveIntegerField(default=0, null=True)),
                ('total', models.PositiveIntegerField(default=0, null=True)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_reservacion_especial', to='hotel.oferta')),
                ('reservacion_especial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_especial', to='reservacion_especial.reservacion_especial')),
            ],
        ),
    ]
