# Generated by Django 4.1.2 on 2022-12-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion_especial', '0004_alter_reservacion_especial_ofeta_especial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_reservacion_especial',
            name='adultos',
        ),
        migrations.RemoveField(
            model_name='items_reservacion_especial',
            name='cantidad_habitaciones',
        ),
        migrations.RemoveField(
            model_name='items_reservacion_especial',
            name='ninnos',
        ),
        migrations.RemoveField(
            model_name='items_reservacion_especial',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='items_reservacion_especial',
            name='total',
        ),
        migrations.RemoveField(
            model_name='reservacion_especial',
            name='transporte',
        ),
        migrations.AddField(
            model_name='reservacion_especial',
            name='adultos',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservacion_especial',
            name='cantidad_habitaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservacion_especial',
            name='ninnos',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
