# Generated by Django 4.1.2 on 2022-12-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion_especial', '0005_remove_items_reservacion_especial_adultos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion_especial',
            old_name='ofeta_especial',
            new_name='oferta_especial',
        ),
    ]
