# Generated by Django 4.1.2 on 2022-12-15 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion_especial', '0006_rename_ofeta_especial_reservacion_especial_oferta_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_especial',
            name='precio_del_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
